version: '3.1'
services:
    zfaka:
        image: baiyuetribe/zfaka  
        restart: always
        ports:
            - 3002:80        
        volumes:
            - /opt/zfaka:/usr/share/nginx/html        
        networks:
            - frontend
            - backend
        depends_on:
            - mysql
    mysql:
        image: mysql:5.5
        volumes:
            - /opt/zfaka/mysql:/var/lib/mysql
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_DATABASE: faka
            MYSQL_ROOT_PASSWORD: baiyue.one
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        depends_on:
            - nginx
        environment:
            PMA_HOST: mysql
            TZ: 'Asia/Shanghai'
        networks:
            - backend
    kodexplorer:
        image: baiyuetribe/kodexplorer
        volumes:
            - /opt/zfaka:/var/www/zfaka       
        ports:
            - 999:80
        depends_on:
            - php
                 
networks:
    frontend:
    backend:

