version: '2'
services:
    nginx:
        image: "zsnmwy/zfaka:nginx"
        restart: always
        container_name: nginx-zfaka
        ports:
            - "810:80"
        networks:
            - frontend
        depends_on:
            - php
            - mysql
    php:
        image: "newfuture/yaf "
        restart: always
        container_name: php-zfaka
        networks:
            - frontend
            - backend

    mysql:
        image: "mysql:5.5"
        restart: always
        container_name: mysql-zfaka
        environment:
          TZ: 'Asia/Shanghai'
          MYSQL_DATABASE: zfaka
          MYSQL_ROOT_PASSWORD: baiyueone
        volumes:
          - /opt/zfaka/mysql:/var/lib/mysql
        networks:
            - backend

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin-zfaka
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
        - 8089:80
      volumes:
        - /sessions
      networks:
        - backend
networks:
    frontend:
    backend:
